#if !canImport(ObjectiveC)
import XCTest

extension OAuth1AuthenticatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OAuth1AuthenticatorTests = [
        ("testApply", testApply),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OAuth1AuthenticatorTests.__allTests__OAuth1AuthenticatorTests),
    ]
}
#endif
